# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinde-cli" do
  desc "Kinde CLI utility"
  homepage "https://kinde.com"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinde"

  on_macos do
    url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.0.10/kinde-cli_mac-os_all.tar.gz"
    sha256 "ddf012610cff37aa1110b0f2d4793c3945b37776e9a7979999334d46fbc00fe1"
  end

  on_linux do
    on_intel do
      url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.0.10/kinde-cli_linux_x86_64.tar.gz"
      sha256 "5f2a85af67dd52b354f6639c38c9dab2f9def66957d33e3bbb4bcf862ce4aea5"
    end
    on_arm do
      url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.0.10/kinde-cli_linux_arm64.tar.gz"
      sha256 "2b9d8db8dec571d15ea1b8dde31a1fd24698b31b99861b9df2826da923bfac34"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kinde"]
    end
  end

  caveats do
    "Thank you for installing Kinde CLI, if this is your first time using the CLI, be sure to run `kinde login` first."
  end

  # No zap stanza required
end
