# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinde-cli" do
  desc "Kinde CLI utility"
  homepage "https://kinde.com"
  version "0.1.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinde"

  on_macos do
    url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.1.15/kinde-cli_mac-os_all.tar.gz"
    sha256 "df136a1fc63e8b9372f82de0bbc6910bde57c611f6ec44688a91754a32a768b6"
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kinde"]
    end
  end

  caveats do
    "Thank you for installing Kinde CLI, if this is your first time using the CLI, be sure to run `kinde login` first."
  end

  # No zap stanza required
end
