# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinde-cli@0.1.16-beta3" do
  desc "Kinde CLI utility"
  homepage "https://kinde.com"
  version "0.1.16-beta3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinde"

  on_macos do
    url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.1.16-beta3/kinde-cli_mac-os_all.tar.gz"
    sha256 "202a9ea27952433913d8df76d53a005a75465bc6f54aaa0c57f1ca5530e42a89"
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kinde"]
    end
  end

  caveats do
    "Thank you for installing Kinde CLI, if this is your first time using the CLI, be sure to run `kinde login` first."
  end

  # No zap stanza required
end
