# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinde-cli" do
  desc "Kinde CLI utility"
  homepage "https://kinde.com"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinde-cli"
  bash_completion "kinde-completion.bash"
  zsh_completion "kinde-completion.zsh"

  on_macos do
    url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.0.7/kinde-cli_mac-os_all.tar.gz"
    sha256 "4d974932baad291ffc8ab518f034b9ea1369071e4d6602eb8d956f2b97afead6"
  end

  on_linux do
    on_intel do
      url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.0.7/kinde-cli_linux_x86_64.tar.gz"
      sha256 "3bc96dc725e25191ab2779e6b7629a7cbbe93e10153fd4b1935a295d04629c05"
    end
    on_arm do
      url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.0.7/kinde-cli_linux_arm64.tar.gz"
      sha256 "45f0f364dc62c6636ac1cfda0f8e56d167d538eeec9275611234c8d8bf5faf31"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kinde"]
    end
  end

  caveats do
    "Thank you for installing Kinde CLI, if this is your first time using the CLI, be sure to run `kinde login` first."
  end

  # No zap stanza required
end
