# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinde-cli@0" do
  name "kinde-cli@0"
  desc "Kinde CLI utility"
  homepage "https://kinde.com"
  version "0.1.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinde"

  on_macos do
    url "https://github.com/kinde-oss/kinde-cli/releases/download/v#{version}/kinde-cli_mac-os_all.tar.gz"
    sha256 "4ca49a6b1b983ee26f38644a72247c3a1f4b3025800ca2148531c47274baaca4"
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kinde"]
    end
  end

  caveats do
    "Thank you for installing Kinde CLI, if this is your first time using the CLI, be sure to run `kinde login` first."
  end

  # No zap stanza required
end
