# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinde-cli@0.0.16-beta1" do
  desc "Kinde CLI utility"
  homepage "https://kinde.com"
  version "0.0.16-beta1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinde"

  on_linux do
    on_intel do
      url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.0.16-beta1/kinde-cli_linux_x86_64.tar.gz"
      sha256 "7ca66744a66452bd741c0a0714e15bf5c34528125da8887ad0ecd7e54de47c3e"
    end
    on_arm do
      url "https://github.com/kinde-oss/kinde-cli/releases/download/v0.0.16-beta1/kinde-cli_linux_arm64.tar.gz"
      sha256 "c4884ca5105f49d56696973dcaac8d1cae53fa4feb6bb05f2afa0268754f2e28"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kinde"]
    end
  end

  caveats do
    "Thank you for installing Kinde CLI, if this is your first time using the CLI, be sure to run `kinde login` first."
  end

  # No zap stanza required
end
